github: [fabiocaccamo]
polar: fabiocaccamo
ko_fi: fabiocaccamo
liberapay: fabiocaccamo
tidelift: pypi/django-validate-email-strict
custom: ["https://www.buymeacoffee.com/fabiocaccamo", "https://www.paypal.me/fabiocaccamo"]
